import type { Player, PlayerStats } from '../types/player'

const stats = (
  shooting: number,
  passing: number,
  dribbling: number,
  defending: number,
  physical: number,
  creativity: number,
): PlayerStats => ({
  shooting,
  passing,
  dribbling,
  defending,
  physical,
  creativity,
})

export const MOCK_PLAYERS: Player[] = [
  {
    id: '1',
    player_name: 'Xavi Simons',
    position: 'CAM',
    league: 'Bundesliga',
    age: 21,
    nationality: 'Netherlands',
    actual_market_value_eur: 40_000_000,
    predicted_value_eur: 55_000_000,
    market_status: 'Undervalued',
    stats: stats(72, 88, 85, 45, 68, 90),
    similar_players: [
      { name: 'Alex Scott', similarity_score: 0.89, price: 15_000_000, position: 'CAM', age: 21, league: 'Premier League' },
      { name: 'Oscar Gloukh', similarity_score: 0.87, price: 12_000_000, position: 'CAM', age: 20, league: 'Israeli PL' },
    ],
    compare_with: { name: 'Kevin De Bruyne', stats: stats(82, 95, 78, 55, 72, 98) },
  },
  {
    id: '2',
    player_name: 'Alex Scott',
    position: 'CAM',
    league: 'Premier League',
    age: 21,
    nationality: 'England',
    actual_market_value_eur: 15_000_000,
    predicted_value_eur: 22_000_000,
    market_status: 'Undervalued',
    stats: stats(68, 84, 80, 50, 70, 85),
    compare_with: { name: 'Kevin De Bruyne', stats: stats(82, 95, 78, 55, 72, 98) },
  },
  {
    id: '3',
    player_name: 'Oscar Gloukh',
    position: 'CAM',
    league: 'Israeli PL',
    age: 20,
    nationality: 'Israel',
    actual_market_value_eur: 12_000_000,
    predicted_value_eur: 18_000_000,
    market_status: 'Undervalued',
    stats: stats(70, 82, 83, 42, 65, 86),
    compare_with: { name: 'Kevin De Bruyne', stats: stats(82, 95, 78, 55, 72, 98) },
  },
  {
    id: '4',
    player_name: 'Kevin De Bruyne',
    position: 'CAM',
    league: 'Premier League',
    age: 33,
    nationality: 'Belgium',
    actual_market_value_eur: 25_000_000,
    predicted_value_eur: 22_000_000,
    market_status: 'Overvalued',
    stats: stats(82, 95, 78, 55, 72, 98),
  },
  {
    id: '5',
    player_name: 'Rodri',
    position: 'CDM',
    league: 'Premier League',
    age: 28,
    nationality: 'Spain',
    actual_market_value_eur: 110_000_000,
    predicted_value_eur: 105_000_000,
    market_status: 'Fair',
    stats: stats(65, 88, 72, 88, 82, 75),
  },
  {
    id: '6',
    player_name: 'Warren Zaïre-Emery',
    position: 'CDM',
    league: 'Ligue 1',
    age: 18,
    nationality: 'France',
    actual_market_value_eur: 60_000_000,
    predicted_value_eur: 75_000_000,
    market_status: 'Undervalued',
    stats: stats(62, 82, 78, 75, 80, 70),
    compare_with: { name: 'Rodri', stats: stats(65, 88, 72, 88, 82, 75) },
  },
  {
    id: '7',
    player_name: 'Erling Haaland',
    position: 'FW',
    league: 'Premier League',
    age: 24,
    nationality: 'Norway',
    actual_market_value_eur: 180_000_000,
    predicted_value_eur: 175_000_000,
    market_status: 'Fair',
    stats: stats(96, 62, 72, 35, 88, 58),
  },
  {
    id: '8',
    player_name: 'Viktor Gyökeres',
    position: 'FW',
    league: 'Primeira Liga',
    age: 26,
    nationality: 'Sweden',
    actual_market_value_eur: 45_000_000,
    predicted_value_eur: 62_000_000,
    market_status: 'Undervalued',
    stats: stats(88, 58, 75, 40, 85, 55),
    compare_with: { name: 'Erling Haaland', stats: stats(96, 62, 72, 35, 88, 58) },
  },
  {
    id: '9',
    player_name: 'William Saliba',
    position: 'DF',
    league: 'Premier League',
    age: 23,
    nationality: 'France',
    actual_market_value_eur: 80_000_000,
    predicted_value_eur: 88_000_000,
    market_status: 'Undervalued',
    stats: stats(35, 72, 65, 92, 85, 45),
  },
  {
    id: '10',
    player_name: 'Gianluigi Donnarumma',
    position: 'GK',
    league: 'Ligue 1',
    age: 26,
    nationality: 'Italy',
    actual_market_value_eur: 45_000_000,
    predicted_value_eur: 40_000_000,
    market_status: 'Overvalued',
    stats: stats(15, 55, 30, 88, 82, 25),
  },
  {
    id: '11',
    player_name: 'Lamine Yamal',
    position: 'RW',
    league: 'La Liga',
    age: 17,
    nationality: 'Spain',
    actual_market_value_eur: 150_000_000,
    predicted_value_eur: 140_000_000,
    market_status: 'Fair',
    stats: stats(78, 82, 92, 38, 68, 88),
  },
  {
    id: '12',
    player_name: 'Mathys Tel',
    position: 'LW',
    league: 'Bundesliga',
    age: 19,
    nationality: 'France',
    actual_market_value_eur: 35_000_000,
    predicted_value_eur: 48_000_000,
    market_status: 'Undervalued',
    stats: stats(80, 70, 88, 35, 72, 78),
    compare_with: { name: 'Lamine Yamal', stats: stats(78, 82, 92, 38, 68, 88) },
  },
]

export const POSITIONS = ['Tất cả', 'GK', 'DF', 'CDM', 'MF', 'CAM', 'LW', 'RW', 'FW'] as const
export const LEAGUES = ['Tất cả', 'Premier League', 'La Liga', 'Bundesliga', 'Serie A', 'Ligue 1', 'Primeira Liga', 'Israeli PL'] as const

export const QUICK_REPLIES = [
  'Định giá Xavi Simons',
  'Tìm CDM giống Rodri giá < 30 củ',
  'Tìm cầu thủ giống De Bruyne giá dưới 20 củ',
  'Cầu thủ Undervalued dưới 25 tuổi',
] as const
